name: real_time_vehicle_tracking_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.1
  web_socket_channel: ^2.2.0
  gpx: ^2.2.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
